# Generated by Django 5.2.14 on 2026-05-26 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(unique=True)),
                ('question_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_answer', models.CharField(max_length=200)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.client_waiver')),
                ('feedback_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.feedback_questions')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('selection', models.CharField(max_length=200)),
                ('client_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.client_waiver')),
            ],
        ),
        migrations.CreateModel(
            name='Waxing_Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.BooleanField(default=False, verbose_name='Medicine')),
                ('allergy', models.BooleanField(default=False, verbose_name='Bee Allergy')),
                ('soap_use', models.BooleanField(default=False, verbose_name='Skin Care Use')),
                ('exposed', models.BooleanField(default=False, verbose_name='Light Exposure')),
                ('health_issues', models.BooleanField(default=False, verbose_name='Health Conditions')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('agreement', models.CharField(max_length=100)),
                ('client_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.client_waiver')),
            ],
        ),
    ]
