# Generated by Django 6.0.5 on 2026-06-10 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_feedback_question_feedback_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_waiver',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
