# Generated by Django 6.0.6 on 2026-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_client_waiver_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='selection',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_name',
        ),
        migrations.AddField(
            model_name='services',
            name='color',
            field=models.BooleanField(default=False, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='services',
            name='hairstyle',
            field=models.BooleanField(default=False, verbose_name='hairstyle'),
        ),
        migrations.AddField(
            model_name='services',
            name='nails',
            field=models.BooleanField(default=False, verbose_name='nails'),
        ),
        migrations.AddField(
            model_name='services',
            name='perm',
            field=models.BooleanField(default=False, verbose_name='perm'),
        ),
        migrations.AddField(
            model_name='services',
            name='waxing',
            field=models.BooleanField(default=False, verbose_name='waxing'),
        ),
    ]
