# Generated by Django 6.0.6 on 2026-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_services_selection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='client',
            new_name='client_info',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_answer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='questions',
        ),
        migrations.AddField(
            model_name='feedback',
            name='q1',
            field=models.BooleanField(default=False, verbose_name='Question #1'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q2',
            field=models.BooleanField(default=False, verbose_name='Question #2'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q3',
            field=models.BooleanField(default=False, verbose_name='Question #3'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q4',
            field=models.BooleanField(default=False, verbose_name='Question #4'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q5',
            field=models.BooleanField(default=False, verbose_name='Question #5'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q6',
            field=models.BooleanField(default=False, verbose_name='Question #6'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q7',
            field=models.BooleanField(default=False, verbose_name='Question #7'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q8',
            field=models.BooleanField(default=False, verbose_name='Question #8'),
        ),
    ]
