# Generated by Django 6.1 on 2026-09-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_client_feedback_client_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waxing_waiver',
            name='client_info',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_message',
            field=models.TextField(blank=True),
        ),
    ]
