# Generated by Django 6.1 on 2026-09-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_waxing_waiver_client_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
